### PR TITLE
Safer backend

### LINKED ISSUE #10: Safer backend
Congrats on the app – it looks and feels great.

I have concerns about how the app persists data. 

The app saves data on quit. This is problematic because if it crashes or if it is terminated unexpected (by user or system) -  notes/changes won't be saved. My suggestion is to save changes as they happen.

The app saves all notes in a single JSON file. If something goes wrong during writing, the file will not be parsable and all notes will essentially be lost to users. My suggestion is to use one file per note.

### PR DESCRIPTION
**Pull request by vixalien**
fixes #10

@sonnyp please review 😁️

### CODE REVIEW

**Comment by vixalien** [comment]
you can try and test if the app automatically picks up your old notes, then converts them into the new storage scheme seamlessy

File: src/store.ts [hunk 1]
```diff
@@ -0,0 +1,269 @@
...
+  // const etag = GLib.compute_checksum_for_string(
+  //   GLib.ChecksumType.MD5,
+  //   string,
+  //   string.length,
+  // );
+
+  return file.replace_contents_async(
+    encoder.encode(string),
+    null,
+    false,
```
Comment (sonnyp) [inline src/store.ts:101]: > If make_backup is TRUE, this function will attempt to make a backup of file. Internally, it uses g_file_replace(), so will try to replace the file contents in the safest way possible. For example, atomic renames are used when replacing local files’ contents.

https://docs.gtk.org/gio/method.File.replace_contents.html

it's a but unclear from the documentation if that means `make_backup` should be set to `true` for "the safest way possible".

Could you try and see if the backup file persists?

File: src/view.ts [hunk 2]
```diff
@@ -319,6 +323,22 @@ export class WriteableStickyNote extends AbstractStickyNote {
...
+    if (!this.note) return;
+    if (this.source) GLib.source_remove(this.source);
+    this.source = this.buffer.connect("modified-changed", (buffer) => {
+      if (buffer.get_modified()) {
+        save_note(this.note!)
+          .then(() => {
+            this.buffer.set_modified(false);
+          });
+      }
+    });
```
Comment (sonnyp) [inline src/view.ts:341]: :+1:

**Review by sonnyp — COMMENTED** [review]
Fixes https://github.com/vixalien/sticky/issues/10 :+1: 

Thanks!

File: src/store.ts (hunk 1 above)
Comment (vixalien) [reply src/store.ts:101]: you mean I should set the "make_backup" option to true?

what do you mean by "see if the backup file persists"

File: src/view.ts (hunk 2 above)
Comment (vixalien) [reply src/view.ts:341]: also should be noted that we can't save during "vfunc_shutdown" as it doesn't wait for promises ("save" is a promise now) to resolve. but that doesn't matter anyways since the files are saved on each click

File: src/store.ts (hunk 1 above)
Comment (sonnyp) [reply src/store.ts:101]: I meant to see if `make_backup` keeps the backup file after `replace_contents` is finished.

File: src/application.ts [hunk 3]
```diff
@@ -62,13 +60,12 @@ export class Application extends Adw.Application {
...
-    this.show_all_notes = data.state.all_notes;
+    load_notes()
+      .then((notes) => {
+        notes.forEach((note) => this.notes_list.append(note));
 
-    data.notes.forEach((note) => this.notes_list.append(note));
-
-    this.sort_notes();
+        this.sort_notes();
+      });
```
Comment (sonnyp) [inline src/application.ts:68]:
```suggestion
      }).catch(logError);
```

File: src/view.ts [hunk 4]
```diff
@@ -319,6 +323,22 @@ export class WriteableStickyNote extends AbstractStickyNote {
...
+
+  add_modified_listener() {
+    if (!this.note) return;
+    if (this.source) GLib.source_remove(this.source);
+    this.source = this.buffer.connect("modified-changed", (buffer) => {
+      if (buffer.get_modified()) {
+        save_note(this.note!)
+          .then(() => {
+            this.buffer.set_modified(false);
+          });
```
Comment (sonnyp) [inline src/view.ts:339]:
```suggestion
          }).catch(logError);
```

**Review by sonnyp — COMMENTED** [review]
unless I missed something - you should handle errors here so they're not silent

File: src/store.ts (hunk 1 above)
Comment (vixalien) [reply src/store.ts:101]: I think note (pun intended)...
